added githooks for gitflow :2.1.0

diff --git a/.githooks/commit-msg b/.githooks/commit-msg
--- a/.githooks/commit-msg
+++ b/.githooks/commit-msg
@@ -11,9 +11,13 @@ fi
 
 # regex to validate in commit msg
 commit_regex='(:[0-9]\.[0-9]\.[0-9])'
-error_msg="Aborting commit. Your commit message is missing the version tag eg '2.0.0'"
+error_msg="Error: Aborting commit. Your commit message is missing the version tag."
+error_msg2="Please add a version tag to your commit message. For example: 'fixing bug for forecasting :1.0.0'"
 
 if ! grep -iqE "$commit_regex" "$1"; then
+  echo ""
   echo "$error_msg" >&2
+  echo "$error_msg2" >&2
+  echo ""
   exit 1
 fi
