testing release

diff --git a/.github/workflows/openbb-gitflow.yml b/.github/workflows/openbb-gitflow.yml
--- a/.github/workflows/openbb-gitflow.yml
+++ b/.github/workflows/openbb-gitflow.yml
@@ -10,32 +10,20 @@ concurrency:
 
 jobs:
   check-branch-name:
-    name: Enforce branch names on all branches.
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
-      - run: |
-          echo "Branch name: $GITHUB_REF"
-          valid_branch_names=(
-            "refs/heads/main"
-            "refs/heads/develop"
-            "refs/heads/release/\d+.\d+.\d+.*"
-            "refs/heads/hotfix/*"
-            "refs/heads/feature/*"
-          )
-          valid=false
-          for pattern in "${valid_branch_names[@]}"; do
-            if [[ "$GITHUB_REF" =~ $pattern ]]; then
-              valid=true
-              break
-            fi
-          done
-          if $valid; then
-            echo "Branch name is valid."
-          else
-            echo "Branch name is invalid."
-            exit 1
-          fi
+    - uses: actions/checkout@v2
+    - run: |
+        if [ "${GITHUB_REF}" == "refs/heads/main" ] ||
+           [ "${GITHUB_REF}" == "refs/heads/develop" ] ||
+           [ "${GITHUB_REF#refs/heads/release/\d+.\d+.\d+.*}" != "$GITHUB_REF" ] ||
+           [ "${GITHUB_REF#refs/heads/hotfix/}" != "$GITHUB_REF" ] ||
+           [ "${GITHUB_REF#refs/heads/feature/}" != "$GITHUB_REF" ]; then
+          echo "Branch name is valid."
+        else
+          echo "Branch name is invalid."
+          exit 1
+        fi
 
   release-pr-restriction:
     name: Restrict any PRs to the release branch. Only allow PRs from the develop branch.
